name: Build Switch App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Switch Dev
        run: |
          dkp-pacman -Syu --noconfirm switch-dev

      - name: Build
        run: make

      - name: Upload NRO
        uses: actions/upload-artifact@v3
        with:
          name: R2D2-Controller
          path: ./*.nro
